.equ STACK_SIZE, 0X22000
.equ ADR_HINT, 0x600000000000
.global relocate_stack
.extern _start

relocate_stack:
    mov %rdx, %r12 # save dl_fini

    mov $9, %rax # __NR_MMAP
    movabs $ADR_HINT, %rdi
    mov $STACK_SIZE, %rsi
    mov $3, %rdx # PROT_READ | PROT_WRITE
    mov $34, %r10 # MAP_ANONYMOUS | MAP_PRIVATE
    mov $-1, %r8
    xor %r9, %r9
    syscall

    xor %rdi, %rdi # M
    xor %r11, %r11 # AT_RANDOM vec
    mov %rsp, %r8
    lea 8(%r8), %r8

_scan_argv:
    mov (%r8), %r9
    test %r9, %r9
    jz _scan_argv_exit

    cmp %rdi, %r9
    jbe _inc_argv
    mov %r9, %rdi

_inc_argv:
    lea 8(%r8), %r8
    jmp _scan_argv

_scan_argv_exit:
    lea 8(%r8), %r8

_scan_envp:
    mov (%r8), %r9
    test %r9, %r9
    jz _scan_envp_exit

    cmp %rdi, %r9
    jbe _inc_envp
    mov %r9, %rdi

_inc_envp:
    lea 8(%r8), %r8
    jmp _scan_envp

_scan_envp_exit:
    lea 8(%r8), %r8

_scan_auxv:
    mov (%r8), %r9
    test %r9, %r9
    jz _scan_auxv_exit

    cmp $7, %r9 # AT_BASE
    je _check_auxp
    cmp $15, %r9 # AT_PLATFORM
    je _check_auxp
    cmp $25, %r9 # AT_RANDOM
    je _check_auxp
    cmp $31, %r9 # AT_EXECFN
    je _check_auxp
    jmp _inc_auxv

_check_auxp:
    mov 8(%r8), %r10
    cmp %rdi, %r10
    jbe _inc_auxv

    mov %r10, %rdi
    xor %r11, %r11

    cmp $25, %r9 # AT_RANDOM
    sete %r11b
    movzx %r11b, %r11

_inc_auxv:
    lea 16(%r8), %r8
    jmp _scan_auxv

_scan_auxv_exit:
    lea 16(%r8), %r8

    mov %rax, %rdx # save mmap'd adr to use rax w/ scasb

    test %r11, %r11
    jnz _at_rnd_highest

    xor %al, %al
    mov $-1, %rcx
    repne scasb 
    jmp _patch

_at_rnd_highest:
    lea 16(%rdi), %rdi

_patch:
    # rdi = M
    # %rdx mmap'd region
    
    mov %rdi, %rcx
    sub %rsp, %rcx # rcx = M - rsp (Stack size)
    inc %rcx

    # Let N be the stack size, A the starting address of the mmap'd region
    # I need to copy the byte range from (M, rsp]
    # to the area (A+N, N] 

    mov %rsp, %rsi # movsb source
    lea STACK_SIZE(%rdx), %rdi # movsb dest
    sub %rcx, %rdi

    and $-16, %rdi

    mov %rdi, %rax

    rep movsb

    mov %rax, %r9
    sub %rsp, %r9 # Delta

    lea 8(%rax), %r10 # &argv[0]

_patch_argv:
    mov (%r10), %r11
    test %r11, %r11
    jz _patch_argv_exit

    add %r9, %r11
    mov %r11, (%r10)

    lea 8(%r10), %r10
    jmp _patch_argv

_patch_argv_exit:
    lea 8(%r10), %r10

_patch_envp:
    mov (%r10), %r11
    test %r11, %r11
    jz _patch_envp_exit

    add %r9, %r11
    mov %r11, (%r10)

    lea 8(%r10), %r10
    jmp _patch_envp

_patch_envp_exit:
    lea 8(%r10), %r10
    
_patch_auxv:
    mov (%r10), %r11
    test %r11, %r11
    jz _patch_auxv_exit

    mov 8(%r10), %r11
    cmp %r11, %rsp
    jl _patch_inc_auxv

    add %r9, %r11
    mov %r11, (%r10)

_patch_inc_auxv:
    lea 16(%r10), %r10
    jmp _patch_auxv

_patch_auxv_exit:
    mov %rax, %rsp

    mov %r12, %rdx

    jmp _start